name: Linting

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linting:
    name: "Linting"
    uses: SocketDev/workflows/.github/workflows/reusable-base.yml@master
    with:
      no-lockfile: true
      npm-test-script: 'check'
