name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    uses: SocketDev/workflows/.github/workflows/reusable-base.yml@master
    with:
      no-lockfile: true
      npm-test-script: 'test-ci'
      node-versions: '14,16,18,19'
      # We currently have some issues on Windows that will have to wait to be fixed
      # os: 'ubuntu-latest,windows-latest'
      os: 'ubuntu-latest'
